plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.majornutcracker.reactnativeselectablewebview'
version = '1.1.0'

android {
  namespace "com.majornutcracker.reactnativeselectablewebview"
  defaultConfig {
    versionCode 2
    versionName "1.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
